language: generic

matrix:
  include:
    - os: linux
      sudo: false
      env: CXX=g++-5
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5', 'libstdc++-5-dev' ]
    - os: linux
      sudo: false
      env: CXX=clang++
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: linux
      sudo: false
      env: CXX=clang++ CXXFLAGS="-fsanitize=address"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++-5-dev' ]
    - os: osx
      osx_image: xcode7.3

cache: apt

install:
  - | 
    if [[ ${CXX} =~ "clang" ]] && [[ $(uname -s) == "Linux" ]]; then
      mkdir mason && curl -sSfL https://github.com/mapbox/mason/archive/v0.5.0.tar.gz | tar --gunzip --extract --strip-components=1 --directory=./mason
      ./.mason/mason install clang++ 3.9.1
      export PATH=$(./.mason/mason prefix clang++ 3.9.1)/bin:${PATH}
      which clang++
    fi

script:
  - make
  - make test
